# This file is part of Bileto.
# Copyright 2022-2023 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3'

services:
    php:
        image: bileto:dev
        build: .
        restart: unless-stopped
        volumes:
            - ../..:/var/www/html:z
            - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:z
        user: $USER

    worker:
        image: bileto:dev
        build: .
        restart: unless-stopped
        command: php bin/console messenger:consume async scheduler_default -vv
        volumes:
            - ../..:/var/www/html:z
            - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:z
        user: $USER

    bundler:
        image: node:20-alpine
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ../..:/app:z
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ../..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z

    pgsql:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        profiles:
            - pgsql

    mariadb:
        image: mariadb:10.4
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: mariadb
        profiles:
            - mariadb

    mailserver:
        image: greenmail/standalone:2.0.0
        restart: unless-stopped
        ports:
            - "3025:3025"
            - "3143:3143"

    ldap:
        image: bitnami/openldap:2
        ports:
            - "1389:1389"
            - "1636:1636"
        environment:
            - LDAP_ROOT=dc=example,dc=com
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=secret
            - BITNAMI_DEBUG=true
        volumes:
            - ./ldap-ldifs:/ldifs:z
        profiles:
            - ldap
