# This file is part of Bileto.
# Copyright 2022-2025 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

name: bileto

services:
    php:
        image: bileto:php-dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        volumes:
            - ../..:/var/www/html:z
            - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:z
        user: $USER

    worker:
        image: bileto:php-dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php bin/console messenger:consume async scheduler_default -vv
        volumes:
            - ../..:/var/www/html:z
            - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini:z
        user: $USER

    bundler:
        image: bileto:dev-node
        build:
            context: .
            dockerfile: Dockerfile.node
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ../..:/app:z
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "${PORT:-8000}:80"
        volumes:
            - ../..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z

    pgsql:
        image: postgres:13-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        profiles:
            - pgsql

    mariadb:
        image: mariadb:10.6
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: mariadb
            MARIADB_AUTO_UPGRADE: 1
        profiles:
            - mariadb

    mailserver:
        image: greenmail/standalone:2.1.0
        restart: unless-stopped
        ports:
            - "3025:3025"
            - "3143:3143"

    ldap:
        image: bitnamilegacy/openldap:2
        ports:
            - "1389:1389"
            - "1636:1636"
        environment:
            - LDAP_ROOT=dc=example,dc=com
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=secret
            - BITNAMI_DEBUG=true
        volumes:
            - ./ldap:/ldifs:z
