# This file is part of Bileto.
# Copyright 2022-2025 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(APP_BASE_URL)%'

when@prod:
    framework:
        router:
            strict_requirements: null
