# This file is part of Bileto.
# Copyright 2022-2026 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            custom_authenticators:
                - App\Security\FormLoginAuthenticator

            logout:
                path: logout
                csrf_token_manager: security.csrf.token_manager

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                token_provider:
                    doctrine: true

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/about, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/passwords/reset, role: PUBLIC_ACCESS }
        - { path: ^/passwords/(\w+)/edit, role: PUBLIC_ACCESS }
        - { path: ^/session/locale, role: PUBLIC_ACCESS }
        - { path: ^/app.manifest, role: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
