# This file is part of Bileto.
# Copyright 2022-2025 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

when@prod:
    sentry:
        dsn: '%env(string:default::SENTRY_DSN)%'
        register_error_listener: false
        register_error_handler: false
        options:
            release: '%app.version%'
            send_default_pii: '%env(bool:SENTRY_SEND_DEFAULT_PII)%'
