# This file is part of Bileto.
# Copyright 2022-2024 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            release: '%app.version%'
