# This file is part of Bileto.
# Copyright 2022-2025 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

framework:
    default_locale: en_GB
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en_GB
        providers:
