# This file is part of Bileto.
# Copyright 2022-2024 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        errors: []
        error: null

when@test:
    twig:
        strict_variables: true
