# This file is part of Bileto.
# Copyright 2022-2024 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/bileto_theme.html.twig']
    globals:
        errors: []
        error: null
    file_name_pattern: '*.twig'

    paths:
        '%kernel.project_dir%/public': public

when@test:
    twig:
        strict_variables: true
