<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\MariaDBPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// phpcs:disable Generic.Files.LineLength
final class Version20260210142718CreateMessageTemplate extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the message_template table';
    }

    public function up(Schema $schema): void
    {
        $dbPlatform = $this->connection->getDatabasePlatform();
        if ($dbPlatform instanceof PostgreSQLPlatform) {
            $this->addSql('CREATE TABLE message_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, content TEXT NOT NULL, type VARCHAR(32) NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_9E46DB92539B0606 ON message_template (uid)');
            $this->addSql('CREATE INDEX IDX_9E46DB92B03A8386 ON message_template (created_by_id)');
            $this->addSql('CREATE INDEX IDX_9E46DB92896DBBDE ON message_template (updated_by_id)');
            $this->addSql('ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) ON DELETE SET NULL NOT DEFERRABLE');
            $this->addSql('ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "users" (id) ON DELETE SET NULL NOT DEFERRABLE');
        } elseif ($dbPlatform instanceof MariaDBPlatform) {
            $this->addSql('CREATE TABLE message_template (id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, type VARCHAR(32) NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_9E46DB92539B0606 (uid), INDEX IDX_9E46DB92B03A8386 (created_by_id), INDEX IDX_9E46DB92896DBBDE (updated_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
            $this->addSql('ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92B03A8386 FOREIGN KEY (created_by_id) REFERENCES `users` (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `users` (id) ON DELETE SET NULL');
        }
    }

    public function down(Schema $schema): void
    {
        $dbPlatform = $this->connection->getDatabasePlatform();
        if ($dbPlatform instanceof PostgreSQLPlatform) {
            $this->addSql('ALTER TABLE message_template DROP CONSTRAINT FK_9E46DB92B03A8386');
            $this->addSql('ALTER TABLE message_template DROP CONSTRAINT FK_9E46DB92896DBBDE');
            $this->addSql('DROP TABLE message_template');
        } elseif ($dbPlatform instanceof MariaDBPlatform) {
            $this->addSql('ALTER TABLE message_template DROP FOREIGN KEY FK_9E46DB92B03A8386');
            $this->addSql('ALTER TABLE message_template DROP FOREIGN KEY FK_9E46DB92896DBBDE');
            $this->addSql('DROP TABLE message_template');
        }
    }
}
