<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\MariaDBPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

// phpcs:disable Generic.Files.LineLength
final class Version20260224132054CreateTask extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the task table';
    }

    public function up(Schema $schema): void
    {
        $dbPlatform = $this->connection->getDatabasePlatform();
        if ($dbPlatform instanceof PostgreSQLPlatform) {
            $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, label VARCHAR(255) NOT NULL, start_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, ticket_id INT NOT NULL, message_id INT DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_527EDB25539B0606 ON task (uid)');
            $this->addSql('CREATE INDEX IDX_527EDB25700047D2 ON task (ticket_id)');
            $this->addSql('CREATE INDEX IDX_527EDB25537A1329 ON task (message_id)');
            $this->addSql('CREATE INDEX IDX_527EDB25B03A8386 ON task (created_by_id)');
            $this->addSql('CREATE INDEX IDX_527EDB25896DBBDE ON task (updated_by_id)');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE SET NULL NOT DEFERRABLE');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25B03A8386 FOREIGN KEY (created_by_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        } elseif ($dbPlatform instanceof MariaDBPlatform) {
            $this->addSql('CREATE TABLE task (id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label VARCHAR(255) NOT NULL, start_at DATETIME NOT NULL, end_at DATETIME NOT NULL, finished_at DATETIME DEFAULT NULL, ticket_id INT NOT NULL, message_id INT DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, UNIQUE INDEX UNIQ_527EDB25539B0606 (uid), INDEX IDX_527EDB25700047D2 (ticket_id), INDEX IDX_527EDB25537A1329 (message_id), INDEX IDX_527EDB25B03A8386 (created_by_id), INDEX IDX_527EDB25896DBBDE (updated_by_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25B03A8386 FOREIGN KEY (created_by_id) REFERENCES `users` (id) ON DELETE CASCADE');
            $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `users` (id) ON DELETE CASCADE');
        }
    }

    public function down(Schema $schema): void
    {
        $dbPlatform = $this->connection->getDatabasePlatform();
        if ($dbPlatform instanceof PostgreSQLPlatform) {
            $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25700047D2');
            $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25537A1329');
            $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25B03A8386');
            $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25896DBBDE');
            $this->addSql('DROP TABLE task');
        } elseif ($dbPlatform instanceof MariaDBPlatform) {
            $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25700047D2');
            $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25537A1329');
            $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25B03A8386');
            $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25896DBBDE');
            $this->addSql('DROP TABLE task');
        }
    }
}
