<?php

// This file is part of Bileto.
// Copyright 2022-2025 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251121150558 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the message_template table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE message_template (' .
            'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ' .
            'uid VARCHAR(20) NOT NULL, ' .
            'created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ' .
            'updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, ' .
            'name VARCHAR(255) NOT NULL, ' .
            'content TEXT DEFAULT NULL, ' .
            'type VARCHAR(20) NOT NULL, ' .
            'time_spent INT NOT NULL, ' .
            'created_by_id INT DEFAULT NULL, ' .
            'updated_by_id INT DEFAULT NULL, ' .
            'PRIMARY KEY(id))'
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9E46DB92539B0606 ON message_template (uid)');
        $this->addSql('CREATE INDEX IDX_9E46DB92B03A8386 ON message_template (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9E46DB92896DBBDE ON message_template (updated_by_id)');
        $this->addSql(
            'ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92B03A8386 ' .
            'FOREIGN KEY (created_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
        $this->addSql(
            'ALTER TABLE message_template ADD CONSTRAINT FK_9E46DB92896DBBDE ' .
            'FOREIGN KEY (updated_by_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE message_template DROP CONSTRAINT FK_9E46DB92B03A8386');
        $this->addSql('ALTER TABLE message_template DROP CONSTRAINT FK_9E46DB92896DBBDE');
        $this->addSql('DROP TABLE message_template');
    }
}
