# This file is part of Bileto.
# Copyright 2022-2023 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3'

services:
    php:
        image: bileto:dev
        build: .
        restart: unless-stopped
        volumes:
            - ..:/var/www/html:z
        user: $USER
        links:
            - database

    worker:
        image: bileto:dev
        build: .
        restart: unless-stopped
        command: php bin/console messenger:consume async scheduler_default -vv
        volumes:
            - ..:/var/www/html:z
        user: $USER
        links:
            - database

    bundler:
        image: node:18-alpine
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ..:/app:z
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        links:
            - php

    database:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    # database:
    #     image: mariadb:10.4
    #     restart: unless-stopped
    #     environment:
    #       - MARIADB_ROOT_PASSWORD=mariadb

    mailserver:
        image: greenmail/standalone:2.0.0
        restart: unless-stopped
        ports:
            - "3025:3025"
            - "3143:3143"
