# This file is part of Bileto.
# Copyright 2022-2023 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
