# This file is part of Bileto.
# Copyright 2022-2025 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(VERSION_FILE): '%kernel.project_dir%/VERSION.txt'

    app.default_uploads_directory: '%kernel.project_dir%/var/uploads'
    app.public_directory: "%kernel.project_dir%/public"
    app.uploads_directory: '%env(default:app.default_uploads_directory:APP_UPLOADS_DIRECTORY)%'
    app.version: '%env(trim:file:VERSION_FILE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Misc/AdditionalTranslations.php'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Command\SeedsCommand:
        arguments:
            - '%kernel.environment%'

    App\Security\Encryptor:
        arguments:
            - '%kernel.project_dir%/var/data/encrypt.key'

    App\Twig\EsbuildAssetExtension:
        arguments:
            - "assets"

    App\Twig\IconExtension:
        arguments:
            - "%kernel.project_dir%/public/icons.svg"

    App\Twig\SettingsExtension:
        arguments:
            - "%kernel.project_dir%/var/settings/logo.svg"

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        tags:
            - ldap

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            - host: '%env(LDAP_HOST)%'
              version: '%env(int:LDAP_VERSION)%'
              port: '%env(int:LDAP_PORT)%'
              encryption: '%env(LDAP_ENCRYPTION)%'

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Twig\EsbuildAssetExtension:
            arguments:
                - "dev_assets"

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Factory\:
            resource: '../tests/Factory'
